version: '3.10'

services:
  csuot:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - migration

  migration:
    build: .
    command: alembic upgrade head
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=csuot
    expose:
      - 5432

volumes:
  postgres_data: